version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "12345:12345"  # Mapeia a porta do container para a porta do host

  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    depends_on:
      - server
    tty: true